[pytest]
testpaths = tests
python_files = test_*.py
addopts = -ra -p no:langsmith
filterwarnings =
    ignore:urllib3 .* doesn't match a supported version!:requests.exceptions.RequestsDependencyWarning
